/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.do365.interview;
import java.util.Date;
import java.text.SimpleDateFormat;
public class App {
    public String getGreeting() {
       SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        return df.format(new Date());
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
